import type { SupabaseClient } from '@supabase/supabase-js';
import { PDFService } from '@/features/agreements/services/pdf.service';

export class ApprovalCertificateService {
  constructor(private supabase: SupabaseClient) {}

  async generate(
    agencyId: string,
    approval: {
      id: string;
      approval_number?: string | null;
      title: string;
      client_signed_at?: string | null;
      clients?: { name?: string; email?: string } | null;
    },
    agencyName: string,
  ): Promise<{ storagePath: string; generatedAt: string }> {
    const signedLabel = approval.client_signed_at
      ? new Date(approval.client_signed_at).toLocaleString('en-AU')
      : new Date().toLocaleString('en-AU');

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: Inter, Helvetica, Arial, sans-serif; color: #111111; padding: 48px; }
    h1 { font-size: 22px; letter-spacing: 0.04em; margin-bottom: 32px; }
    p { font-size: 12px; line-height: 1.6; margin: 8px 0; }
    .muted { color: #64748b; font-size: 10px; margin-top: 40px; }
  </style>
</head>
<body>
  <h1>CERTIFICATE OF APPROVAL</h1>
  <p><strong>Agency:</strong> ${escapeHtml(agencyName)}</p>
  <p><strong>Application:</strong> ${escapeHtml(approval.approval_number || approval.title)}</p>
  <p><strong>Client:</strong> ${escapeHtml(approval.clients?.name || 'Client')}</p>
  ${approval.clients?.email ? `<p><strong>Email:</strong> ${escapeHtml(approval.clients.email)}</p>` : ''}
  <p style="margin-top:24px;">The client has reviewed and approved the application package for lodgement.</p>
  <p><strong>Signed:</strong> ${escapeHtml(signedLabel)}</p>
  <p class="muted">Generated by ImmiMate for compliance record-keeping.</p>
</body>
</html>`;

    const bytes = await PDFService.generatePdf(html);
    const generatedAt = new Date().toISOString();
    const storagePath = `${agencyId}/approvals/${approval.id}/certificate-of-approval.pdf`;

    const { error } = await this.supabase.storage
      .from('documents')
      .upload(storagePath, bytes, {
        contentType: 'application/pdf',
        upsert: true,
      });

    if (error) throw new Error(`Certificate upload failed: ${error.message}`);

    return { storagePath, generatedAt };
  }
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
